# -*- coding: utf-8 -*-
"""oss 과제 - 2545287 이지윤.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18EfHREvD72W7MsvYkwxKVYnPofHXyXGR
"""

from sklearn import datasets, metrics
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor

# 1. 데이터셋 로드 (운동 데이터)
linnerud = datasets.load_linnerud()
data = linnerud.data
target = linnerud.target

print(f"데이터 크기: {data.shape}")

# 2. train/test split
X_train, X_test, y_train, y_test = train_test_split(
    data, target, test_size=0.2, random_state=42
)
# 3. 머신러닝 모델 학습 (회귀)
knn_reg = KNeighborsRegressor(n_neighbors=4)
knn_reg.fit(X_train, y_train)

# 4. 예측 및 평가 출력
y_pred = knn_reg.predict(X_test)

mse = metrics.mean_squared_error(y_test, y_pred)
print(f"k-NN 회귀 모델 (k=4) MSE (평균 제곱 오차): {mse:.4f}")